/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'

const SetupLazyRouteImport = createFileRoute('/setup')()
const R500LazyRouteImport = createFileRoute('/500')()
const PublicSignUpLazyRouteImport = createFileRoute('/_public/sign-up')()
const PublicSignInLazyRouteImport = createFileRoute('/_public/sign-in')()
const AuthenticatedSettingsLazyRouteImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedLogsLazyRouteImport = createFileRoute(
  '/_authenticated/logs',
)()
const AuthenticatedDashboardLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const AuthenticatedApiKeysLazyRouteImport = createFileRoute(
  '/_authenticated/api-keys',
)()
const AuthenticatedVisionIndexLazyRouteImport = createFileRoute(
  '/_authenticated/vision/',
)()
const AuthenticatedServicesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/services/',
)()
const AuthenticatedMarketplaceIndexLazyRouteImport = createFileRoute(
  '/_authenticated/marketplace/',
)()
const AuthenticatedGroupsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/groups/',
)()
const AuthenticatedConnectionsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/connections/',
)()
const AuthenticatedCamerasIndexLazyRouteImport = createFileRoute(
  '/_authenticated/cameras/',
)()
const AuthenticatedVisionCreateLazyRouteImport = createFileRoute(
  '/_authenticated/vision/create',
)()
const AuthenticatedVisionIdLazyRouteImport = createFileRoute(
  '/_authenticated/vision/$id',
)()
const AuthenticatedServicesCreateLazyRouteImport = createFileRoute(
  '/_authenticated/services/create',
)()
const AuthenticatedServicesIdLazyRouteImport = createFileRoute(
  '/_authenticated/services/$id',
)()
const AuthenticatedMarketplaceIdLazyRouteImport = createFileRoute(
  '/_authenticated/marketplace/$id',
)()
const AuthenticatedGroupsCreateLazyRouteImport = createFileRoute(
  '/_authenticated/groups/create',
)()
const AuthenticatedGroupsIdLazyRouteImport = createFileRoute(
  '/_authenticated/groups/$id',
)()
const AuthenticatedConnectionsCreateLazyRouteImport = createFileRoute(
  '/_authenticated/connections/create',
)()
const AuthenticatedConnectionsIdLazyRouteImport = createFileRoute(
  '/_authenticated/connections/$id',
)()
const AuthenticatedCamerasCreateLazyRouteImport = createFileRoute(
  '/_authenticated/cameras/create',
)()
const AuthenticatedCamerasIdLazyRouteImport = createFileRoute(
  '/_authenticated/cameras/$id',
)()
const AuthenticatedAdminUsersLazyRouteImport = createFileRoute(
  '/_authenticated/admin/users',
)()
const AuthenticatedAdminSystemLazyRouteImport = createFileRoute(
  '/_authenticated/admin/system',
)()
const AuthenticatedAdminReviewsLazyRouteImport = createFileRoute(
  '/_authenticated/admin/reviews',
)()
const AuthenticatedAdminLogsLazyRouteImport = createFileRoute(
  '/_authenticated/admin/logs',
)()
const AuthenticatedAdminMarketplaceIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/marketplace/',
)()
const AuthenticatedAdminMarketplaceCreateLazyRouteImport = createFileRoute(
  '/_authenticated/admin/marketplace/create',
)()
const AuthenticatedAdminMarketplaceIdLazyRouteImport = createFileRoute(
  '/_authenticated/admin/marketplace/$id',
)()

const SetupLazyRoute = SetupLazyRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/setup.lazy').then((d) => d.Route))
const R500LazyRoute = R500LazyRouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/500.lazy').then((d) => d.Route))
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignUpLazyRoute = PublicSignUpLazyRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRouteRoute,
} as any).lazy(() =>
  import('./routes/_public/sign-up.lazy').then((d) => d.Route),
)
const PublicSignInLazyRoute = PublicSignInLazyRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRouteRoute,
} as any).lazy(() =>
  import('./routes/_public/sign-in.lazy').then((d) => d.Route),
)
const AuthenticatedSettingsLazyRoute =
  AuthenticatedSettingsLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings.lazy').then((d) => d.Route),
  )
const AuthenticatedLogsLazyRoute = AuthenticatedLogsLazyRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/logs.lazy').then((d) => d.Route),
)
const AuthenticatedDashboardLazyRoute =
  AuthenticatedDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
  )
const AuthenticatedApiKeysLazyRoute =
  AuthenticatedApiKeysLazyRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/api-keys.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisionIndexLazyRoute =
  AuthenticatedVisionIndexLazyRouteImport.update({
    id: '/vision/',
    path: '/vision/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/vision/index.lazy').then((d) => d.Route),
  )
const AuthenticatedServicesIndexLazyRoute =
  AuthenticatedServicesIndexLazyRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/services/index.lazy').then((d) => d.Route),
  )
const AuthenticatedMarketplaceIndexLazyRoute =
  AuthenticatedMarketplaceIndexLazyRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/marketplace/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedGroupsIndexLazyRoute =
  AuthenticatedGroupsIndexLazyRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/groups/index.lazy').then((d) => d.Route),
  )
const AuthenticatedConnectionsIndexLazyRoute =
  AuthenticatedConnectionsIndexLazyRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/connections/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedCamerasIndexLazyRoute =
  AuthenticatedCamerasIndexLazyRouteImport.update({
    id: '/cameras/',
    path: '/cameras/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cameras/index.lazy').then((d) => d.Route),
  )
const AuthenticatedVisionCreateLazyRoute =
  AuthenticatedVisionCreateLazyRouteImport.update({
    id: '/vision/create',
    path: '/vision/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/vision/create.lazy').then((d) => d.Route),
  )
const AuthenticatedVisionIdLazyRoute =
  AuthenticatedVisionIdLazyRouteImport.update({
    id: '/vision/$id',
    path: '/vision/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/vision/$id.lazy').then((d) => d.Route),
  )
const AuthenticatedServicesCreateLazyRoute =
  AuthenticatedServicesCreateLazyRouteImport.update({
    id: '/services/create',
    path: '/services/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/services/create.lazy').then((d) => d.Route),
  )
const AuthenticatedServicesIdLazyRoute =
  AuthenticatedServicesIdLazyRouteImport.update({
    id: '/services/$id',
    path: '/services/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/services/$id.lazy').then((d) => d.Route),
  )
const AuthenticatedMarketplaceIdLazyRoute =
  AuthenticatedMarketplaceIdLazyRouteImport.update({
    id: '/marketplace/$id',
    path: '/marketplace/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/marketplace/$id.lazy').then((d) => d.Route),
  )
const AuthenticatedGroupsCreateLazyRoute =
  AuthenticatedGroupsCreateLazyRouteImport.update({
    id: '/groups/create',
    path: '/groups/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/groups/create.lazy').then((d) => d.Route),
  )
const AuthenticatedGroupsIdLazyRoute =
  AuthenticatedGroupsIdLazyRouteImport.update({
    id: '/groups/$id',
    path: '/groups/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/groups/$id.lazy').then((d) => d.Route),
  )
const AuthenticatedConnectionsCreateLazyRoute =
  AuthenticatedConnectionsCreateLazyRouteImport.update({
    id: '/connections/create',
    path: '/connections/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/connections/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedConnectionsIdLazyRoute =
  AuthenticatedConnectionsIdLazyRouteImport.update({
    id: '/connections/$id',
    path: '/connections/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/connections/$id.lazy').then((d) => d.Route),
  )
const AuthenticatedCamerasCreateLazyRoute =
  AuthenticatedCamerasCreateLazyRouteImport.update({
    id: '/cameras/create',
    path: '/cameras/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cameras/create.lazy').then((d) => d.Route),
  )
const AuthenticatedCamerasIdLazyRoute =
  AuthenticatedCamerasIdLazyRouteImport.update({
    id: '/cameras/$id',
    path: '/cameras/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cameras/$id.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminUsersLazyRoute =
  AuthenticatedAdminUsersLazyRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/users.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminSystemLazyRoute =
  AuthenticatedAdminSystemLazyRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/system.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminReviewsLazyRoute =
  AuthenticatedAdminReviewsLazyRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/reviews.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminLogsLazyRoute =
  AuthenticatedAdminLogsLazyRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/logs.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminMarketplaceIndexLazyRoute =
  AuthenticatedAdminMarketplaceIndexLazyRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/marketplace/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminMarketplaceCreateLazyRoute =
  AuthenticatedAdminMarketplaceCreateLazyRouteImport.update({
    id: '/marketplace/create',
    path: '/marketplace/create',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/marketplace/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminMarketplaceIdLazyRoute =
  AuthenticatedAdminMarketplaceIdLazyRouteImport.update({
    id: '/marketplace/$id',
    path: '/marketplace/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/marketplace/$id.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500LazyRoute
  '/setup': typeof SetupLazyRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api-keys': typeof AuthenticatedApiKeysLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/logs': typeof AuthenticatedLogsLazyRoute
  '/settings': typeof AuthenticatedSettingsLazyRoute
  '/sign-in': typeof PublicSignInLazyRoute
  '/sign-up': typeof PublicSignUpLazyRoute
  '/admin/logs': typeof AuthenticatedAdminLogsLazyRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsLazyRoute
  '/admin/system': typeof AuthenticatedAdminSystemLazyRoute
  '/admin/users': typeof AuthenticatedAdminUsersLazyRoute
  '/cameras/$id': typeof AuthenticatedCamerasIdLazyRoute
  '/cameras/create': typeof AuthenticatedCamerasCreateLazyRoute
  '/connections/$id': typeof AuthenticatedConnectionsIdLazyRoute
  '/connections/create': typeof AuthenticatedConnectionsCreateLazyRoute
  '/groups/$id': typeof AuthenticatedGroupsIdLazyRoute
  '/groups/create': typeof AuthenticatedGroupsCreateLazyRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdLazyRoute
  '/services/$id': typeof AuthenticatedServicesIdLazyRoute
  '/services/create': typeof AuthenticatedServicesCreateLazyRoute
  '/vision/$id': typeof AuthenticatedVisionIdLazyRoute
  '/vision/create': typeof AuthenticatedVisionCreateLazyRoute
  '/cameras/': typeof AuthenticatedCamerasIndexLazyRoute
  '/connections/': typeof AuthenticatedConnectionsIndexLazyRoute
  '/groups/': typeof AuthenticatedGroupsIndexLazyRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexLazyRoute
  '/services/': typeof AuthenticatedServicesIndexLazyRoute
  '/vision/': typeof AuthenticatedVisionIndexLazyRoute
  '/admin/marketplace/$id': typeof AuthenticatedAdminMarketplaceIdLazyRoute
  '/admin/marketplace/create': typeof AuthenticatedAdminMarketplaceCreateLazyRoute
  '/admin/marketplace/': typeof AuthenticatedAdminMarketplaceIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500LazyRoute
  '/setup': typeof SetupLazyRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api-keys': typeof AuthenticatedApiKeysLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/logs': typeof AuthenticatedLogsLazyRoute
  '/settings': typeof AuthenticatedSettingsLazyRoute
  '/sign-in': typeof PublicSignInLazyRoute
  '/sign-up': typeof PublicSignUpLazyRoute
  '/admin/logs': typeof AuthenticatedAdminLogsLazyRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsLazyRoute
  '/admin/system': typeof AuthenticatedAdminSystemLazyRoute
  '/admin/users': typeof AuthenticatedAdminUsersLazyRoute
  '/cameras/$id': typeof AuthenticatedCamerasIdLazyRoute
  '/cameras/create': typeof AuthenticatedCamerasCreateLazyRoute
  '/connections/$id': typeof AuthenticatedConnectionsIdLazyRoute
  '/connections/create': typeof AuthenticatedConnectionsCreateLazyRoute
  '/groups/$id': typeof AuthenticatedGroupsIdLazyRoute
  '/groups/create': typeof AuthenticatedGroupsCreateLazyRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdLazyRoute
  '/services/$id': typeof AuthenticatedServicesIdLazyRoute
  '/services/create': typeof AuthenticatedServicesCreateLazyRoute
  '/vision/$id': typeof AuthenticatedVisionIdLazyRoute
  '/vision/create': typeof AuthenticatedVisionCreateLazyRoute
  '/cameras': typeof AuthenticatedCamerasIndexLazyRoute
  '/connections': typeof AuthenticatedConnectionsIndexLazyRoute
  '/groups': typeof AuthenticatedGroupsIndexLazyRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexLazyRoute
  '/services': typeof AuthenticatedServicesIndexLazyRoute
  '/vision': typeof AuthenticatedVisionIndexLazyRoute
  '/admin/marketplace/$id': typeof AuthenticatedAdminMarketplaceIdLazyRoute
  '/admin/marketplace/create': typeof AuthenticatedAdminMarketplaceCreateLazyRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/500': typeof R500LazyRoute
  '/setup': typeof SetupLazyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysLazyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/_authenticated/logs': typeof AuthenticatedLogsLazyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsLazyRoute
  '/_public/sign-in': typeof PublicSignInLazyRoute
  '/_public/sign-up': typeof PublicSignUpLazyRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsLazyRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsLazyRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemLazyRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersLazyRoute
  '/_authenticated/cameras/$id': typeof AuthenticatedCamerasIdLazyRoute
  '/_authenticated/cameras/create': typeof AuthenticatedCamerasCreateLazyRoute
  '/_authenticated/connections/$id': typeof AuthenticatedConnectionsIdLazyRoute
  '/_authenticated/connections/create': typeof AuthenticatedConnectionsCreateLazyRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdLazyRoute
  '/_authenticated/groups/create': typeof AuthenticatedGroupsCreateLazyRoute
  '/_authenticated/marketplace/$id': typeof AuthenticatedMarketplaceIdLazyRoute
  '/_authenticated/services/$id': typeof AuthenticatedServicesIdLazyRoute
  '/_authenticated/services/create': typeof AuthenticatedServicesCreateLazyRoute
  '/_authenticated/vision/$id': typeof AuthenticatedVisionIdLazyRoute
  '/_authenticated/vision/create': typeof AuthenticatedVisionCreateLazyRoute
  '/_authenticated/cameras/': typeof AuthenticatedCamerasIndexLazyRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexLazyRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexLazyRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexLazyRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexLazyRoute
  '/_authenticated/vision/': typeof AuthenticatedVisionIndexLazyRoute
  '/_authenticated/admin/marketplace/$id': typeof AuthenticatedAdminMarketplaceIdLazyRoute
  '/_authenticated/admin/marketplace/create': typeof AuthenticatedAdminMarketplaceCreateLazyRoute
  '/_authenticated/admin/marketplace/': typeof AuthenticatedAdminMarketplaceIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/setup'
    | '/admin'
    | '/api-keys'
    | '/dashboard'
    | '/logs'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/admin/logs'
    | '/admin/reviews'
    | '/admin/system'
    | '/admin/users'
    | '/cameras/$id'
    | '/cameras/create'
    | '/connections/$id'
    | '/connections/create'
    | '/groups/$id'
    | '/groups/create'
    | '/marketplace/$id'
    | '/services/$id'
    | '/services/create'
    | '/vision/$id'
    | '/vision/create'
    | '/cameras/'
    | '/connections/'
    | '/groups/'
    | '/marketplace/'
    | '/services/'
    | '/vision/'
    | '/admin/marketplace/$id'
    | '/admin/marketplace/create'
    | '/admin/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/setup'
    | '/admin'
    | '/api-keys'
    | '/dashboard'
    | '/logs'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/admin/logs'
    | '/admin/reviews'
    | '/admin/system'
    | '/admin/users'
    | '/cameras/$id'
    | '/cameras/create'
    | '/connections/$id'
    | '/connections/create'
    | '/groups/$id'
    | '/groups/create'
    | '/marketplace/$id'
    | '/services/$id'
    | '/services/create'
    | '/vision/$id'
    | '/vision/create'
    | '/cameras'
    | '/connections'
    | '/groups'
    | '/marketplace'
    | '/services'
    | '/vision'
    | '/admin/marketplace/$id'
    | '/admin/marketplace/create'
    | '/admin/marketplace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/500'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/api-keys'
    | '/_authenticated/dashboard'
    | '/_authenticated/logs'
    | '/_authenticated/settings'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/system'
    | '/_authenticated/admin/users'
    | '/_authenticated/cameras/$id'
    | '/_authenticated/cameras/create'
    | '/_authenticated/connections/$id'
    | '/_authenticated/connections/create'
    | '/_authenticated/groups/$id'
    | '/_authenticated/groups/create'
    | '/_authenticated/marketplace/$id'
    | '/_authenticated/services/$id'
    | '/_authenticated/services/create'
    | '/_authenticated/vision/$id'
    | '/_authenticated/vision/create'
    | '/_authenticated/cameras/'
    | '/_authenticated/connections/'
    | '/_authenticated/groups/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/services/'
    | '/_authenticated/vision/'
    | '/_authenticated/admin/marketplace/$id'
    | '/_authenticated/admin/marketplace/create'
    | '/_authenticated/admin/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  R500LazyRoute: typeof R500LazyRoute
  SetupLazyRoute: typeof SetupLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpLazyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInLazyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vision/': {
      id: '/_authenticated/vision/'
      path: '/vision'
      fullPath: '/vision/'
      preLoaderRoute: typeof AuthenticatedVisionIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cameras/': {
      id: '/_authenticated/cameras/'
      path: '/cameras'
      fullPath: '/cameras/'
      preLoaderRoute: typeof AuthenticatedCamerasIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vision/create': {
      id: '/_authenticated/vision/create'
      path: '/vision/create'
      fullPath: '/vision/create'
      preLoaderRoute: typeof AuthenticatedVisionCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vision/$id': {
      id: '/_authenticated/vision/$id'
      path: '/vision/$id'
      fullPath: '/vision/$id'
      preLoaderRoute: typeof AuthenticatedVisionIdLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/create': {
      id: '/_authenticated/services/create'
      path: '/services/create'
      fullPath: '/services/create'
      preLoaderRoute: typeof AuthenticatedServicesCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/$id': {
      id: '/_authenticated/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthenticatedServicesIdLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/$id': {
      id: '/_authenticated/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof AuthenticatedMarketplaceIdLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/create': {
      id: '/_authenticated/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthenticatedGroupsCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/create': {
      id: '/_authenticated/connections/create'
      path: '/connections/create'
      fullPath: '/connections/create'
      preLoaderRoute: typeof AuthenticatedConnectionsCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/$id': {
      id: '/_authenticated/connections/$id'
      path: '/connections/$id'
      fullPath: '/connections/$id'
      preLoaderRoute: typeof AuthenticatedConnectionsIdLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cameras/create': {
      id: '/_authenticated/cameras/create'
      path: '/cameras/create'
      fullPath: '/cameras/create'
      preLoaderRoute: typeof AuthenticatedCamerasCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cameras/$id': {
      id: '/_authenticated/cameras/$id'
      path: '/cameras/$id'
      fullPath: '/cameras/$id'
      preLoaderRoute: typeof AuthenticatedCamerasIdLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marketplace/': {
      id: '/_authenticated/admin/marketplace/'
      path: '/marketplace'
      fullPath: '/admin/marketplace/'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceIndexLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marketplace/create': {
      id: '/_authenticated/admin/marketplace/create'
      path: '/marketplace/create'
      fullPath: '/admin/marketplace/create'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceCreateLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marketplace/$id': {
      id: '/_authenticated/admin/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/admin/marketplace/$id'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceIdLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminLogsLazyRoute: typeof AuthenticatedAdminLogsLazyRoute
  AuthenticatedAdminReviewsLazyRoute: typeof AuthenticatedAdminReviewsLazyRoute
  AuthenticatedAdminSystemLazyRoute: typeof AuthenticatedAdminSystemLazyRoute
  AuthenticatedAdminUsersLazyRoute: typeof AuthenticatedAdminUsersLazyRoute
  AuthenticatedAdminMarketplaceIdLazyRoute: typeof AuthenticatedAdminMarketplaceIdLazyRoute
  AuthenticatedAdminMarketplaceCreateLazyRoute: typeof AuthenticatedAdminMarketplaceCreateLazyRoute
  AuthenticatedAdminMarketplaceIndexLazyRoute: typeof AuthenticatedAdminMarketplaceIndexLazyRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminLogsLazyRoute: AuthenticatedAdminLogsLazyRoute,
    AuthenticatedAdminReviewsLazyRoute: AuthenticatedAdminReviewsLazyRoute,
    AuthenticatedAdminSystemLazyRoute: AuthenticatedAdminSystemLazyRoute,
    AuthenticatedAdminUsersLazyRoute: AuthenticatedAdminUsersLazyRoute,
    AuthenticatedAdminMarketplaceIdLazyRoute:
      AuthenticatedAdminMarketplaceIdLazyRoute,
    AuthenticatedAdminMarketplaceCreateLazyRoute:
      AuthenticatedAdminMarketplaceCreateLazyRoute,
    AuthenticatedAdminMarketplaceIndexLazyRoute:
      AuthenticatedAdminMarketplaceIndexLazyRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedApiKeysLazyRoute: typeof AuthenticatedApiKeysLazyRoute
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
  AuthenticatedLogsLazyRoute: typeof AuthenticatedLogsLazyRoute
  AuthenticatedSettingsLazyRoute: typeof AuthenticatedSettingsLazyRoute
  AuthenticatedCamerasIdLazyRoute: typeof AuthenticatedCamerasIdLazyRoute
  AuthenticatedCamerasCreateLazyRoute: typeof AuthenticatedCamerasCreateLazyRoute
  AuthenticatedConnectionsIdLazyRoute: typeof AuthenticatedConnectionsIdLazyRoute
  AuthenticatedConnectionsCreateLazyRoute: typeof AuthenticatedConnectionsCreateLazyRoute
  AuthenticatedGroupsIdLazyRoute: typeof AuthenticatedGroupsIdLazyRoute
  AuthenticatedGroupsCreateLazyRoute: typeof AuthenticatedGroupsCreateLazyRoute
  AuthenticatedMarketplaceIdLazyRoute: typeof AuthenticatedMarketplaceIdLazyRoute
  AuthenticatedServicesIdLazyRoute: typeof AuthenticatedServicesIdLazyRoute
  AuthenticatedServicesCreateLazyRoute: typeof AuthenticatedServicesCreateLazyRoute
  AuthenticatedVisionIdLazyRoute: typeof AuthenticatedVisionIdLazyRoute
  AuthenticatedVisionCreateLazyRoute: typeof AuthenticatedVisionCreateLazyRoute
  AuthenticatedCamerasIndexLazyRoute: typeof AuthenticatedCamerasIndexLazyRoute
  AuthenticatedConnectionsIndexLazyRoute: typeof AuthenticatedConnectionsIndexLazyRoute
  AuthenticatedGroupsIndexLazyRoute: typeof AuthenticatedGroupsIndexLazyRoute
  AuthenticatedMarketplaceIndexLazyRoute: typeof AuthenticatedMarketplaceIndexLazyRoute
  AuthenticatedServicesIndexLazyRoute: typeof AuthenticatedServicesIndexLazyRoute
  AuthenticatedVisionIndexLazyRoute: typeof AuthenticatedVisionIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedApiKeysLazyRoute: AuthenticatedApiKeysLazyRoute,
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
  AuthenticatedLogsLazyRoute: AuthenticatedLogsLazyRoute,
  AuthenticatedSettingsLazyRoute: AuthenticatedSettingsLazyRoute,
  AuthenticatedCamerasIdLazyRoute: AuthenticatedCamerasIdLazyRoute,
  AuthenticatedCamerasCreateLazyRoute: AuthenticatedCamerasCreateLazyRoute,
  AuthenticatedConnectionsIdLazyRoute: AuthenticatedConnectionsIdLazyRoute,
  AuthenticatedConnectionsCreateLazyRoute:
    AuthenticatedConnectionsCreateLazyRoute,
  AuthenticatedGroupsIdLazyRoute: AuthenticatedGroupsIdLazyRoute,
  AuthenticatedGroupsCreateLazyRoute: AuthenticatedGroupsCreateLazyRoute,
  AuthenticatedMarketplaceIdLazyRoute: AuthenticatedMarketplaceIdLazyRoute,
  AuthenticatedServicesIdLazyRoute: AuthenticatedServicesIdLazyRoute,
  AuthenticatedServicesCreateLazyRoute: AuthenticatedServicesCreateLazyRoute,
  AuthenticatedVisionIdLazyRoute: AuthenticatedVisionIdLazyRoute,
  AuthenticatedVisionCreateLazyRoute: AuthenticatedVisionCreateLazyRoute,
  AuthenticatedCamerasIndexLazyRoute: AuthenticatedCamerasIndexLazyRoute,
  AuthenticatedConnectionsIndexLazyRoute:
    AuthenticatedConnectionsIndexLazyRoute,
  AuthenticatedGroupsIndexLazyRoute: AuthenticatedGroupsIndexLazyRoute,
  AuthenticatedMarketplaceIndexLazyRoute:
    AuthenticatedMarketplaceIndexLazyRoute,
  AuthenticatedServicesIndexLazyRoute: AuthenticatedServicesIndexLazyRoute,
  AuthenticatedVisionIndexLazyRoute: AuthenticatedVisionIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicSignInLazyRoute: typeof PublicSignInLazyRoute
  PublicSignUpLazyRoute: typeof PublicSignUpLazyRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSignInLazyRoute: PublicSignInLazyRoute,
  PublicSignUpLazyRoute: PublicSignUpLazyRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  R500LazyRoute: R500LazyRoute,
  SetupLazyRoute: SetupLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
